services:
  web:
    container_name: pneumonia
    image: pneumonia
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8010:8000"
    expose:
      - "8010"
    env_file:
      - ./.env

  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8011:3306"
    volumes:
      - my-db:/var/lib/mysql
  
volumes:
  my-db: